unpackaged/main/default/objects/GW_Volunteers__Volunteer_Job__c/GW_Volunteers__Volunteer_Job__c.object-meta.xml
<CustomObject>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GW_Volunteers__Volunteer_Job__c/fields/GW_Volunteers__Campaign__c.field-meta.xml
<CustomField>
    <fullName>GW_Volunteers__Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Volunteer Jobs</relationshipLabel>
    <relationshipName>Volunteer_Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/GW_Volunteers__Volunteer_Job__c/fields/Job_header_image__c.field-meta.xml
<CustomField>
    <fullName>Job_header_image__c</fullName>
    <label>Job header image</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/PortalBannerControllerTest.cls
@IsTest
private class PortalBannerControllerTest {
    @IsTest
    static void testGetJobBannerData() {
        Campaign newCampaign = new Campaign(Name = 'Test Campaign');
        insert newCampaign;
        GW_Volunteers__Volunteer_Job__c newJob = new GW_Volunteers__Volunteer_Job__c(
                Name = 'Test Job',
                Job_header_image__c = 'headerUrl',
                GW_Volunteers__Campaign__c = newCampaign.Id
        );
        insert newJob;
        GW_Volunteers__Volunteer_Job__c job = PortalBannerController.getJobBannerData(newJob.Id);
        System.assertEquals(job.Name, 'Test Job', 'Name should match');
        System.assertEquals(job.Job_header_image__c, 'headerUrl', 'Job_header_image__c should match');
    }
}